name: 'Awesome CV Builder'
author: 'Olivier Rodomond'
branding:
  icon: 'file-plus'
  color: 'orange'
description: 'Automate your Awesome CV resume and keep it up to date.'
inputs:
  ACCESS_TOKEN:
    description: 'Depending on the repository permissions you may need to provide the action with a GitHub personal access token instead of the provided GitHub token in order to deploy. This should be stored as a secret.'
    required: false
  FILE_NAME:
    description: 'The filename of your latex document within your repository (Ex: resume.tex)'
    required: true
  LATEST_TAG:
    description: 'Define if you want the action to create a latest tag, allowing you to the latest document though a single tag named "latest" (default: true)'
    required: true
outputs:
  TAG_NAME:
    description: 'The name of the tag created into your repository'
runs:
  using: 'docker'
  image: 'Dockerfile'
