title: 'Gh-CV-Assistant > Installation Issue : Multiple repository'
body: |
  Gh-CV-Assistant can't be installed on multiple repositories at the same time.
  Since the bot supposed to manage your resume, please select only the target repositries one by one.

