title: "Gh-CV-Assistant > Installation issue : Private repositories"
body: |
  Please turn your repository as public.
  The bot is using the API from [latexonline.cc](https://latexonline.cc) to generate the .pdf.
  Latexonline needs to have access to your repository.

